import Head from 'next/head'
import Image from 'next/image'
import { motion } from "framer-motion";
import styles from '../styles/Home.module.css'
import { useScroll } from "../maher/useScroll";
import { headerAnimation, imageAnimation,fromDown,secondAnimation  } from "../maher/Animations";
import Sec2 from '../components/sec2'
export default function Home() {
  const [element, controls] = useScroll();


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div>

  <h1>framer</h1>
</div>

<div className=' h-[140vh]'>
section One

<div className="main-container" ref={element}>

<motion.div
          className="content"
          variants={headerAnimation}
          animate={controls}
          transition={{ delay: 0.2, type: "tween" }}
        >
          <h1>
            We Provide Solutions to Help You to Build or Grow Your Buisness!
          </h1>
          <p className='w-1/3'>
            A professional web and mobile app development agency with over 100+
            web and app developed. We provide a high- quality service in web and
            mobile app development as well as in design.
          </p>

          </motion.div>



  </div>







</div>

<hr/>
 

<Sec2/>



     
    </div>
  )
}
